In [1]:
from sklearn.preprocessing import LabelBinarizer, OneHotEncoder, MultiLabelBinarizer
import pandas as pd
import numpy as np
from ast import literal_eval

In [2]:
df = pd.read_csv('../data/cards_data.csv')
df.head()

,id,name,cmc,mana_cost,colors,legendary,types,sub_types,oracle_text,keywords,power,toughness,textless,rarity,reserved,released_at,booster,usd
0,e882c9f9-bf30-46b6-bedc-379d2c80e5cb,+2 Mace,2.0,{1}{W},['W'],False,['Artifact'],['Equipment'],Equipped creature gets +2/+2.\nEquip {3} ({3}:...,['Equip'],non-creature,non-creature,False,common,False,2021-07-23,True,0.02
1,2a83882c-3e03-4e85-aaac-97fa1d08a772,Aarakocra Sneak,4.0,{3}{U},['U'],False,['Creature'],"['Bird', 'Rogue']",Flying\nWhen Aarakocra Sneak enters the battle...,['Flying'],1,4,False,common,False,2022-06-10,True,0.07
2,c9f1fc97-00c0-492b-a4a3-b179afc2f95d,Abaddon the Despoiler,5.0,{2}{U}{B}{R},"['B', 'R', 'U']",True,['Creature'],"['Astartes', 'Warrior']",Trample\nMark of Chaos Ascendant — During your...,"['Mark of Chaos Ascendant', 'Trample']",5,5,False,mythic,False,2022-10-07,False,2.88
3,4945031e-1158-474c-9e50-1ec817acc767,Abandoned Outpost,0.0,{0},['No Colors'],False,['Land'],['none'],Abandoned Outpost enters the battlefield tappe...,['no keywords'],non-creature,non-creature,False,common,False,2001-10-01,True,0.13
4,23b587f3-5eac-45a7-a048-dd73d2a2b74f,Abandoned Sarcophagus,3.0,{3},['C'],False,['Artifact'],['none'],You may cast spells that have a cycling abilit...,['no keywords'],non-creature,non-creature,False,rare,False,2020-04-17,False,0.08

In [3]:
df[df['name'].str.contains('Kozilek')]

,id,name,cmc,mana_cost,colors,legendary,types,sub_types,oracle_text,keywords,power,toughness,textless,rarity,reserved,released_at,booster,usd
1121,9312fada-fc31-46ac-b6a1-cfffd776856f,Artisan of Kozilek,9.0,{9},['C'],False,['Creature'],['Eldrazi'],"When you cast this spell, you may return targe...",['Annihilator'],10,9,False,uncommon,False,2023-08-04,False,0.50
10227,2a4180ae-1fd9-4185-b4f0-9e8f668a5737,Herald of Kozilek,3.0,{1}{U}{R},['C'],False,['Creature'],"['Eldrazi', 'Drone']",Devoid (This card has no color.)\nColorless sp...,['Devoid'],2,4,False,uncommon,False,2015-10-02,True,0.12
11110,17f38740-20fd-4097-90f8-f0c2c2ff7281,Inquisition of Kozilek,1.0,{B},['B'],False,['Sorcery'],['none'],Target player reveals their hand. You choose a...,['no keywords'],non-creature,non-creature,False,uncommon,False,2022-07-08,True,0.30
12281,d27cf7b7-7982-46bd-a559-7789c0e74bae,"Kozilek, Butcher of Truth",10.0,{10},['C'],True,['Creature'],['Eldrazi'],"When you cast this spell, draw four cards.\nAn...",['Annihilator'],12,12,False,mythic,False,2022-07-08,True,39.69
12282,c550d179-32ec-4ad8-91c2-d79320a21cba,Kozilek's Channeler,5.0,{5},['C'],False,['Creature'],['Eldrazi'],{T}: Add {C}{C}.,['no keywords'],4,4,False,common,False,2015-10-02,True,0.27
12283,b75585bd-fdd8-44d1-8c7c-b96df5fc473e,Kozilek's Pathfinder,6.0,{6},['C'],False,['Creature'],['Eldrazi'],{C}: Target creature can't block Kozilek's Pat...,['no keywords'],5,5,False,common,False,2016-01-22,True,0.11
12284,fa828bc7-0f5a-45de-9608-da42dda8f3f9,Kozilek's Predator,4.0,{3}{G},['G'],False,['Creature'],"['Eldrazi', 'Drone']",When Kozilek's Predator enters the battlefield...,['no keywords'],3,3,False,common,False,2023-08-04,True,0.03
12285,72765559-0a78-4aa3-827e-cb4612720991,Kozilek's Return,3.0,{2}{R},['C'],False,['Instant'],['none'],Devoid (This card has no color.)\nKozilek's Re...,['Devoid'],non-creature,non-creature,False,mythic,False,2016-01-22,True,0.59
12286,786c6a0f-3f75-45ff-aae9-5c866be279d0,Kozilek's Sentinel,2.0,{1}{R},['C'],False,['Creature'],"['Eldrazi', 'Drone']",Devoid (This card has no color.)\nWhenever you...,['Devoid'],1,4,False,common,False,2015-10-02,True,0.05
12287,a384cd5b-2c6c-4969-bb62-a017e2fc9794,Kozilek's Shrieker,3.0,{2}{B},['C'],False,['Creature'],"['Eldrazi', 'Drone']",Devoid (This card has no color.)\n{C}: Kozilek...,['Devoid'],3,2,False,common,False,2016-01-22,True,0.04
12288,d80665ae-fcb2-48fd-95be-8768293bcef7,Kozilek's Translator,5.0,{4}{B},['C'],False,['Creature'],"['Eldrazi', 'Drone']",Devoid (This card has no color.)\nPay 1 life: ...,['Devoid'],3,5,False,common,False,2016-01-22,True,0.03
12289,c41554e7-2a07-4cc7-b01b-44deed08e588,"Kozilek, the Great Distortion",10.0,{8}{C}{C},['C'],True,['Creature'],['Eldrazi'],"When you cast this spell, if you have fewer th...",['Menace'],12,12,False,mythic,False,2023-08-04,True,1.93
13700,48669993-ad68-499e-8f2e-bc5c651b4b28,Maw of Kozilek,4.0,{3}{R},['C'],False,['Creature'],"['Eldrazi', 'Drone']",Devoid (This card has no color.)\n{C}: Maw of ...,['Devoid'],2,5,False,common,False,2016-01-22,True,0.02

In [4]:
df['mana_cost'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 26052 entries, 0 to 26051
Series name: mana_cost
Non-Null Count  Dtype
--------------  -----
25678 non-null  object
dtypes: object(1)
memory usage: 203.7+ KB

In [5]:
df['mana_cost'] = df['mana_cost'].astype(str)
df['mana_cost'].head()

0          {1}{W}
1          {3}{U}
2    {2}{U}{B}{R}
3             {0}
4             {3}
Name: mana_cost, dtype: object

In [6]:
def convertmc(mana_cost):
    return list(mana_cost.replace('{', '').replace('}', ''))
df['mana_cost'] =  df['mana_cost'].apply(convertmc)
df['mana_cost'].head()

0          [1, W]
1          [3, U]
2    [2, U, B, R]
3             [0]
4             [3]
Name: mana_cost, dtype: object

In [7]:
df.drop(columns=['id'], inplace=True)
df.head()

,name,cmc,mana_cost,colors,legendary,types,sub_types,oracle_text,keywords,power,toughness,textless,rarity,reserved,released_at,booster,usd
0,+2 Mace,2.0,"[1, W]",['W'],False,['Artifact'],['Equipment'],Equipped creature gets +2/+2.\nEquip {3} ({3}:...,['Equip'],non-creature,non-creature,False,common,False,2021-07-23,True,0.02
1,Aarakocra Sneak,4.0,"[3, U]",['U'],False,['Creature'],"['Bird', 'Rogue']",Flying\nWhen Aarakocra Sneak enters the battle...,['Flying'],1,4,False,common,False,2022-06-10,True,0.07
2,Abaddon the Despoiler,5.0,"[2, U, B, R]","['B', 'R', 'U']",True,['Creature'],"['Astartes', 'Warrior']",Trample\nMark of Chaos Ascendant — During your...,"['Mark of Chaos Ascendant', 'Trample']",5,5,False,mythic,False,2022-10-07,False,2.88
3,Abandoned Outpost,0.0,[0],['No Colors'],False,['Land'],['none'],Abandoned Outpost enters the battlefield tappe...,['no keywords'],non-creature,non-creature,False,common,False,2001-10-01,True,0.13
4,Abandoned Sarcophagus,3.0,[3],['C'],False,['Artifact'],['none'],You may cast spells that have a cycling abilit...,['no keywords'],non-creature,non-creature,False,rare,False,2020-04-17,False,0.08

In [8]:
df['sub_types'].fillna("['none']", inplace=True)
df.head()

,name,cmc,mana_cost,colors,legendary,types,sub_types,oracle_text,keywords,power,toughness,textless,rarity,reserved,released_at,booster,usd
0,+2 Mace,2.0,"[1, W]",['W'],False,['Artifact'],['Equipment'],Equipped creature gets +2/+2.\nEquip {3} ({3}:...,['Equip'],non-creature,non-creature,False,common,False,2021-07-23,True,0.02
1,Aarakocra Sneak,4.0,"[3, U]",['U'],False,['Creature'],"['Bird', 'Rogue']",Flying\nWhen Aarakocra Sneak enters the battle...,['Flying'],1,4,False,common,False,2022-06-10,True,0.07
2,Abaddon the Despoiler,5.0,"[2, U, B, R]","['B', 'R', 'U']",True,['Creature'],"['Astartes', 'Warrior']",Trample\nMark of Chaos Ascendant — During your...,"['Mark of Chaos Ascendant', 'Trample']",5,5,False,mythic,False,2022-10-07,False,2.88
3,Abandoned Outpost,0.0,[0],['No Colors'],False,['Land'],['none'],Abandoned Outpost enters the battlefield tappe...,['no keywords'],non-creature,non-creature,False,common,False,2001-10-01,True,0.13
4,Abandoned Sarcophagus,3.0,[3],['C'],False,['Artifact'],['none'],You may cast spells that have a cycling abilit...,['no keywords'],non-creature,non-creature,False,rare,False,2020-04-17,False,0.08

#### Cards that transform had nan colors, I will remove them for now

In [9]:
df['types'] = df['types'].apply(literal_eval)
df['sub_types'] = df['sub_types'].apply(literal_eval)
df['keywords'] = df['keywords'].apply(literal_eval)
df.head()

,name,cmc,mana_cost,colors,legendary,types,sub_types,oracle_text,keywords,power,toughness,textless,rarity,reserved,released_at,booster,usd
0,+2 Mace,2.0,"[1, W]",['W'],False,[Artifact],[Equipment],Equipped creature gets +2/+2.\nEquip {3} ({3}:...,[Equip],non-creature,non-creature,False,common,False,2021-07-23,True,0.02
1,Aarakocra Sneak,4.0,"[3, U]",['U'],False,[Creature],"[Bird, Rogue]",Flying\nWhen Aarakocra Sneak enters the battle...,[Flying],1,4,False,common,False,2022-06-10,True,0.07
2,Abaddon the Despoiler,5.0,"[2, U, B, R]","['B', 'R', 'U']",True,[Creature],"[Astartes, Warrior]",Trample\nMark of Chaos Ascendant — During your...,"[Mark of Chaos Ascendant, Trample]",5,5,False,mythic,False,2022-10-07,False,2.88
3,Abandoned Outpost,0.0,[0],['No Colors'],False,[Land],[none],Abandoned Outpost enters the battlefield tappe...,[no keywords],non-creature,non-creature,False,common,False,2001-10-01,True,0.13
4,Abandoned Sarcophagus,3.0,[3],['C'],False,[Artifact],[none],You may cast spells that have a cycling abilit...,[no keywords],non-creature,non-creature,False,rare,False,2020-04-17,False,0.08

In [10]:
rarity_ohe = OneHotEncoder()
rarity_encoded = rarity_ohe.fit_transform(df[['rarity']]).toarray()
rarity_ohe.categories_

[array(['common', 'mythic', 'rare', 'special', 'uncommon'], dtype=object)]

In [11]:
column_names = rarity_ohe.get_feature_names_out(['rarity'])
df_encoded = pd.DataFrame(rarity_encoded, columns=column_names)
df_encoded.head()

   rarity_common  rarity_mythic  rarity_rare  rarity_special  rarity_uncommon
0            1.0            0.0          0.0             0.0              0.0
1            1.0            0.0          0.0             0.0              0.0
2            0.0            1.0          0.0             0.0              0.0
3            1.0            0.0          0.0             0.0              0.0
4            0.0            0.0          1.0             0.0              0.0

In [12]:
df = pd.concat([df, df_encoded], axis=1)
df.drop(columns='rarity', inplace=True)
df.head()

,name,cmc,mana_cost,colors,legendary,types,sub_types,oracle_text,keywords,power,...,textless,reserved,released_at,booster,usd,rarity_common,rarity_mythic,rarity_rare,rarity_special,rarity_uncommon
0,+2 Mace,2.0,"[1, W]",['W'],False,[Artifact],[Equipment],Equipped creature gets +2/+2.\nEquip {3} ({3}:...,[Equip],non-creature,...,False,False,2021-07-23,True,0.02,1.0,0.0,0.0,0.0,0.0
1,Aarakocra Sneak,4.0,"[3, U]",['U'],False,[Creature],"[Bird, Rogue]",Flying\nWhen Aarakocra Sneak enters the battle...,[Flying],1,...,False,False,2022-06-10,True,0.07,1.0,0.0,0.0,0.0,0.0
2,Abaddon the Despoiler,5.0,"[2, U, B, R]","['B', 'R', 'U']",True,[Creature],"[Astartes, Warrior]",Trample\nMark of Chaos Ascendant — During your...,"[Mark of Chaos Ascendant, Trample]",5,...,False,False,2022-10-07,False,2.88,0.0,1.0,0.0,0.0,0.0
3,Abandoned Outpost,0.0,[0],['No Colors'],False,[Land],[none],Abandoned Outpost enters the battlefield tappe...,[no keywords],non-creature,...,False,False,2001-10-01,True,0.13,1.0,0.0,0.0,0.0,0.0
4,Abandoned Sarcophagus,3.0,[3],['C'],False,[Artifact],[none],You may cast spells that have a cycling abilit...,[no keywords],non-creature,...,False,False,2020-04-17,False,0.08,0.0,0.0,1.0,0.0,0.0

In [13]:
df.colors.value_counts()

colors
['W']                        3921
['B']                        3884
['R']                        3848
['U']                        3812
['G']                        3802
['C']                        2371
['No Colors']                 906
[nan]                         352
['B', 'R']                    291
['U', 'W']                    288
['G', 'W']                    284
['B', 'U']                    283
['G', 'R']                    274
['G', 'U']                    245
['R', 'W']                    243
['R', 'U']                    239
['B', 'W']                    239
['B', 'G']                    226
['B', 'R', 'U']                78
['B', 'U', 'W']                64
['G', 'R', 'W']                62
['G', 'U', 'W']                60
['B', 'G', 'R']                60
['B', 'G', 'R', 'U', 'W']      42
['R', 'U', 'W']                41
['G', 'R', 'U']                32
['B', 'R', 'W']                32
['B', 'G', 'U']                30
['B', 'G', 'W']                29
['G', 'R', 'U', 'W']            5
['B', 'G', 'U', 'W']            3
['B', 'R', 'U', 'W']            2
['B', 'G', 'R', 'W']            2
['B', 'G', 'R', 'U']            2
Name: count, dtype: int64

In [14]:
df[df['colors']=='[nan]'].head()

,name,cmc,mana_cost,colors,legendary,types,sub_types,oracle_text,keywords,power,...,textless,reserved,released_at,booster,usd,rarity_common,rarity_mythic,rarity_rare,rarity_special,rarity_uncommon
17,Aberrant Researcher // Perfected Form,4.0,"[n, a, n]",[nan],False,[Creature],"[Human, Insect, //, Creature, —, Insect, Horror]",NaN,"[Flying, Transform, Mill]",non-creature,...,False,False,2016-04-08,True,0.03,0.0,0.0,0.0,0.0,1.0
97,Accursed Witch // Infectious Curse,4.0,"[n, a, n]",[nan],False,[Creature],"[Human, Shaman, //, Enchantment, —, Aura, Curse]",NaN,"[Transform, Enchant]",non-creature,...,False,False,2016-04-08,True,0.26,0.0,0.0,0.0,0.0,1.0
108,"Aclazotz, Deepest Betrayal // Temple of the Dead",5.0,"[n, a, n]",[nan],True,[Creature],"[Bat, God, //, Land]",NaN,"[Flying, Lifelink, Transform]",non-creature,...,False,False,2023-11-17,True,3.03,0.0,1.0,0.0,0.0,0.0
212,Aetherblade Agent // Gitaxian Mindstinger,2.0,"[n, a, n]",[nan],False,[Creature],"[Human, Rogue, //, Creature, —, Phyrexian, Rogue]",NaN,"[Transform, Deathtouch]",non-creature,...,False,False,2023-04-21,True,0.02,1.0,0.0,0.0,0.0,0.0
269,Afflicted Deserter // Werewolf Ransacker,4.0,"[n, a, n]",[nan],False,[Creature],"[Human, Werewolf, //, Creature, —, Werewolf]",NaN,[Transform],non-creature,...,False,False,2012-02-03,True,0.25,0.0,0.0,0.0,0.0,1.0

In [15]:
df.drop(df[df['colors']=='[nan]'].index, inplace=True)
df.reset_index(drop=True)
df.head()

,name,cmc,mana_cost,colors,legendary,types,sub_types,oracle_text,keywords,power,...,textless,reserved,released_at,booster,usd,rarity_common,rarity_mythic,rarity_rare,rarity_special,rarity_uncommon
0,+2 Mace,2.0,"[1, W]",['W'],False,[Artifact],[Equipment],Equipped creature gets +2/+2.\nEquip {3} ({3}:...,[Equip],non-creature,...,False,False,2021-07-23,True,0.02,1.0,0.0,0.0,0.0,0.0
1,Aarakocra Sneak,4.0,"[3, U]",['U'],False,[Creature],"[Bird, Rogue]",Flying\nWhen Aarakocra Sneak enters the battle...,[Flying],1,...,False,False,2022-06-10,True,0.07,1.0,0.0,0.0,0.0,0.0
2,Abaddon the Despoiler,5.0,"[2, U, B, R]","['B', 'R', 'U']",True,[Creature],"[Astartes, Warrior]",Trample\nMark of Chaos Ascendant — During your...,"[Mark of Chaos Ascendant, Trample]",5,...,False,False,2022-10-07,False,2.88,0.0,1.0,0.0,0.0,0.0
3,Abandoned Outpost,0.0,[0],['No Colors'],False,[Land],[none],Abandoned Outpost enters the battlefield tappe...,[no keywords],non-creature,...,False,False,2001-10-01,True,0.13,1.0,0.0,0.0,0.0,0.0
4,Abandoned Sarcophagus,3.0,[3],['C'],False,[Artifact],[none],You may cast spells that have a cycling abilit...,[no keywords],non-creature,...,False,False,2020-04-17,False,0.08,0.0,0.0,1.0,0.0,0.0

In [16]:
df.colors.value_counts()

colors
['W']                        3921
['B']                        3884
['R']                        3848
['U']                        3812
['G']                        3802
['C']                        2371
['No Colors']                 906
['B', 'R']                    291
['U', 'W']                    288
['G', 'W']                    284
['B', 'U']                    283
['G', 'R']                    274
['G', 'U']                    245
['R', 'W']                    243
['R', 'U']                    239
['B', 'W']                    239
['B', 'G']                    226
['B', 'R', 'U']                78
['B', 'U', 'W']                64
['G', 'R', 'W']                62
['G', 'U', 'W']                60
['B', 'G', 'R']                60
['B', 'G', 'R', 'U', 'W']      42
['R', 'U', 'W']                41
['G', 'R', 'U']                32
['B', 'R', 'W']                32
['B', 'G', 'U']                30
['B', 'G', 'W']                29
['G', 'R', 'U', 'W']            5
['B', 'G', 'U', 'W']            3
['B', 'R', 'U', 'W']            2
['B', 'G', 'R', 'W']            2
['B', 'G', 'R', 'U']            2
Name: count, dtype: int64

In [17]:
df['colors'].replace("['No Colors']", "['N']", inplace=True)
df['colors'].value_counts().head(7)

colors
['W']    3921
['B']    3884
['R']    3848
['U']    3812
['G']    3802
['C']    2371
['N']     906
Name: count, dtype: int64

In [18]:
df['colors']=df['colors'].apply(literal_eval)
df['colors'].head()

0          [W]
1          [U]
2    [B, R, U]
3          [N]
4          [C]
Name: colors, dtype: object

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 25700 entries, 0 to 26051
Data columns (total 21 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   name             25700 non-null  object
 1   cmc              25700 non-null  float64
 2   mana_cost        25700 non-null  object
 3   colors           25700 non-null  object
 4   legendary        25700 non-null  bool
 5   types            25700 non-null  object
 6   sub_types        25700 non-null  object
 7   oracle_text      25099 non-null  object
 8   keywords         25700 non-null  object
 9   power            25700 non-null  object
 10  toughness        25700 non-null  object
 11  textless         25700 non-null  bool
 12  reserved         25700 non-null  bool
 13  released_at      25700 non-null  object
 14  booster          25700 non-null  bool
 15  usd              25643 non-null  float64
 16  rarity_common    25700 non-null  float64
 17  rarity_mythic    25700 non-null  float64
 18  rarity_rare      25700 non-null  float64
 19  rarity_special   25700 non-null  float64
 20  rarity_uncommon  25700 non-null  float64
dtypes: bool(4), float64(7), object(10)
memory usage: 3.6+ MB

In [20]:
df.reset_index(drop=True, inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25700 entries, 0 to 25699
Data columns (total 21 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   name             25700 non-null  object
 1   cmc              25700 non-null  float64
 2   mana_cost        25700 non-null  object
 3   colors           25700 non-null  object
 4   legendary        25700 non-null  bool
 5   types            25700 non-null  object
 6   sub_types        25700 non-null  object
 7   oracle_text      25099 non-null  object
 8   keywords         25700 non-null  object
 9   power            25700 non-null  object
 10  toughness        25700 non-null  object
 11  textless         25700 non-null  bool
 12  reserved         25700 non-null  bool
 13  released_at      25700 non-null  object
 14  booster          25700 non-null  bool
 15  usd              25643 non-null  float64
 16  rarity_common    25700 non-null  float64
 17  rarity_mythic    25700 non-null  float64
 18  rarity_rare      25700 non-null  float64
 19  rarity_special   25700 non-null  float64
 20  rarity_uncommon  25700 non-null  float64
dtypes: bool(4), float64(7), object(10)
memory usage: 3.4+ MB

In [21]:
colors_mlb = MultiLabelBinarizer()
colors_mlb.fit(df['colors'])
colors_mlb.classes_

array(['B', 'C', 'G', 'N', 'R', 'U', 'W'], dtype=object)

In [22]:
binary_colors = colors_mlb.transform(df['colors'])
colors_df = pd.DataFrame(binary_colors, columns=colors_mlb.classes_)
colors_df

       B  C  G  N  R  U  W
0      0  0  0  0  0  0  1
1      0  0  0  0  0  1  0
2      1  0  0  0  1  1  0
3      0  0  0  1  0  0  0
4      0  1  0  0  0  0  0
...   .. .. .. .. .. .. ..
25695  1  0  0  0  1  0  1
25696  0  0  0  0  0  1  0
25697  1  0  0  0  0  1  1
25698  0  0  0  0  1  0  0
25699  0  0  0  0  0  1  0

[25700 rows x 7 columns]

In [23]:
df.drop('colors', axis=1, inplace=True)
df.head()

,name,cmc,mana_cost,legendary,types,sub_types,oracle_text,keywords,power,toughness,textless,reserved,released_at,booster,usd,rarity_common,rarity_mythic,rarity_rare,rarity_special,rarity_uncommon
0,+2 Mace,2.0,"[1, W]",False,[Artifact],[Equipment],Equipped creature gets +2/+2.\nEquip {3} ({3}:...,[Equip],non-creature,non-creature,False,False,2021-07-23,True,0.02,1.0,0.0,0.0,0.0,0.0
1,Aarakocra Sneak,4.0,"[3, U]",False,[Creature],"[Bird, Rogue]",Flying\nWhen Aarakocra Sneak enters the battle...,[Flying],1,4,False,False,2022-06-10,True,0.07,1.0,0.0,0.0,0.0,0.0
2,Abaddon the Despoiler,5.0,"[2, U, B, R]",True,[Creature],"[Astartes, Warrior]",Trample\nMark of Chaos Ascendant — During your...,"[Mark of Chaos Ascendant, Trample]",5,5,False,False,2022-10-07,False,2.88,0.0,1.0,0.0,0.0,0.0
3,Abandoned Outpost,0.0,[0],False,[Land],[none],Abandoned Outpost enters the battlefield tappe...,[no keywords],non-creature,non-creature,False,False,2001-10-01,True,0.13,1.0,0.0,0.0,0.0,0.0
4,Abandoned Sarcophagus,3.0,[3],False,[Artifact],[none],You may cast spells that have a cycling abilit...,[no keywords],non-creature,non-creature,False,False,2020-04-17,False,0.08,0.0,0.0,1.0,0.0,0.0

In [24]:
df = pd.concat([df, colors_df], axis=1)
df.head()

,name,cmc,mana_cost,legendary,types,sub_types,oracle_text,keywords,power,toughness,...,rarity_rare,rarity_special,rarity_uncommon,B,C,G,N,R,U,W
0,+2 Mace,2.0,"[1, W]",False,[Artifact],[Equipment],Equipped creature gets +2/+2.\nEquip {3} ({3}:...,[Equip],non-creature,non-creature,...,0.0,0.0,0.0,0,0,0,0,0,0,1
1,Aarakocra Sneak,4.0,"[3, U]",False,[Creature],"[Bird, Rogue]",Flying\nWhen Aarakocra Sneak enters the battle...,[Flying],1,4,...,0.0,0.0,0.0,0,0,0,0,0,1,0
2,Abaddon the Despoiler,5.0,"[2, U, B, R]",True,[Creature],"[Astartes, Warrior]",Trample\nMark of Chaos Ascendant — During your...,"[Mark of Chaos Ascendant, Trample]",5,5,...,0.0,0.0,0.0,1,0,0,0,1,1,0
3,Abandoned Outpost,0.0,[0],False,[Land],[none],Abandoned Outpost enters the battlefield tappe...,[no keywords],non-creature,non-creature,...,0.0,0.0,0.0,0,0,0,1,0,0,0
4,Abandoned Sarcophagus,3.0,[3],False,[Artifact],[none],You may cast spells that have a cycling abilit...,[no keywords],non-creature,non-creature,...,1.0,0.0,0.0,0,1,0,0,0,0,0

In [25]:
legend_binarizer = LabelBinarizer()
df['legendary'] = legend_binarizer.fit_transform(df['legendary'])
df['legendary'].head()

0    0
1    0
2    1
3    0
4    0
Name: legendary, dtype: int64

In [26]:
textless_binarizer = LabelBinarizer()
df['textless'] = textless_binarizer.fit_transform(df['textless'])
df['textless'].head()

0    0
1    0
2    0
3    0
4    0
Name: textless, dtype: int64

In [27]:
reserved_binarizer = LabelBinarizer()
df['reserved'] = textless_binarizer.fit_transform(df['reserved'])
df['reserved'].head()

0    0
1    0
2    0
3    0
4    0
Name: reserved, dtype: int64

In [28]:
booster_binarizer = LabelBinarizer()
df['booster'] = textless_binarizer.fit_transform(df['booster'])
df['booster'].head()

0    1
1    1
2    0
3    1
4    0
Name: booster, dtype: int64

In [29]:
df.head()

,name,cmc,mana_cost,legendary,types,sub_types,oracle_text,keywords,power,toughness,...,rarity_rare,rarity_special,rarity_uncommon,B,C,G,N,R,U,W
0,+2 Mace,2.0,"[1, W]",0,[Artifact],[Equipment],Equipped creature gets +2/+2.\nEquip {3} ({3}:...,[Equip],non-creature,non-creature,...,0.0,0.0,0.0,0,0,0,0,0,0,1
1,Aarakocra Sneak,4.0,"[3, U]",0,[Creature],"[Bird, Rogue]",Flying\nWhen Aarakocra Sneak enters the battle...,[Flying],1,4,...,0.0,0.0,0.0,0,0,0,0,0,1,0
2,Abaddon the Despoiler,5.0,"[2, U, B, R]",1,[Creature],"[Astartes, Warrior]",Trample\nMark of Chaos Ascendant — During your...,"[Mark of Chaos Ascendant, Trample]",5,5,...,0.0,0.0,0.0,1,0,0,0,1,1,0
3,Abandoned Outpost,0.0,[0],0,[Land],[none],Abandoned Outpost enters the battlefield tappe...,[no keywords],non-creature,non-creature,...,0.0,0.0,0.0,0,0,0,1,0,0,0
4,Abandoned Sarcophagus,3.0,[3],0,[Artifact],[none],You may cast spells that have a cycling abilit...,[no keywords],non-creature,non-creature,...,1.0,0.0,0.0,0,1,0,0,0,0,0

In [30]:
list(df.columns.values)

['name',
 'cmc',
 'mana_cost',
 'legendary',
 'types',
 'sub_types',
 'oracle_text',
 'keywords',
 'power',
 'toughness',
 'textless',
 'reserved',
 'released_at',
 'booster',
 'usd',
 'rarity_common',
 'rarity_mythic',
 'rarity_rare',
 'rarity_special',
 'rarity_uncommon',
 'B',
 'C',
 'G',
 'N',
 'R',
 'U',
 'W']

In [31]:
df = df[['name',
 'cmc',
 'mana_cost',
 'B',
 'C',
 'G',
 'N',
 'R',
 'U',
 'W',
 'legendary',
 'types',
 'sub_types',
 'oracle_text',
 'keywords',
 'power',
 'toughness',
 'textless',
 'reserved',
 'rarity_common',
 'rarity_mythic',
 'rarity_rare',
 'rarity_special',
 'rarity_uncommon',
 'released_at',
 'booster',
 'usd']]
df.head()

,name,cmc,mana_cost,B,C,G,N,R,U,W,...,textless,reserved,rarity_common,rarity_mythic,rarity_rare,rarity_special,rarity_uncommon,released_at,booster,usd
0,+2 Mace,2.0,"[1, W]",0,0,0,0,0,0,1,...,0,0,1.0,0.0,0.0,0.0,0.0,2021-07-23,1,0.02
1,Aarakocra Sneak,4.0,"[3, U]",0,0,0,0,0,1,0,...,0,0,1.0,0.0,0.0,0.0,0.0,2022-06-10,1,0.07
2,Abaddon the Despoiler,5.0,"[2, U, B, R]",1,0,0,0,1,1,0,...,0,0,0.0,1.0,0.0,0.0,0.0,2022-10-07,0,2.88
3,Abandoned Outpost,0.0,[0],0,0,0,1,0,0,0,...,0,0,1.0,0.0,0.0,0.0,0.0,2001-10-01,1,0.13
4,Abandoned Sarcophagus,3.0,[3],0,1,0,0,0,0,0,...,0,0,0.0,0.0,1.0,0.0,0.0,2020-04-17,0,0.08

In [32]:
df[['power', 'toughness']].head()

          power     toughness
0  non-creature  non-creature
1             1             4
2             5             5
3  non-creature  non-creature
4  non-creature  non-creature

#### I deicded that non-creatue cards will now have power toughness of 0

In [33]:
df['power'] = df['power'].replace('non-creature', 0)
df['toughness'] = df['toughness'].replace('non-creature', 0)
df[['power', 'toughness']].head()

  power toughness
0     0         0
1     1         4
2     5         5
3     0         0
4     0         0

#### i decided that mana cost maybe useless at this point since we have cmc and the colors

In [34]:
df.drop(columns='mana_cost', inplace=True)
df.head()

,name,cmc,B,C,G,N,R,U,W,legendary,...,textless,reserved,rarity_common,rarity_mythic,rarity_rare,rarity_special,rarity_uncommon,released_at,booster,usd
0,+2 Mace,2.0,0,0,0,0,0,0,1,0,...,0,0,1.0,0.0,0.0,0.0,0.0,2021-07-23,1,0.02
1,Aarakocra Sneak,4.0,0,0,0,0,0,1,0,0,...,0,0,1.0,0.0,0.0,0.0,0.0,2022-06-10,1,0.07
2,Abaddon the Despoiler,5.0,1,0,0,0,1,1,0,1,...,0,0,0.0,1.0,0.0,0.0,0.0,2022-10-07,0,2.88
3,Abandoned Outpost,0.0,0,0,0,1,0,0,0,0,...,0,0,1.0,0.0,0.0,0.0,0.0,2001-10-01,1,0.13
4,Abandoned Sarcophagus,3.0,0,1,0,0,0,0,0,0,...,0,0,0.0,0.0,1.0,0.0,0.0,2020-04-17,0,0.08

In [35]:
df[df['types'].apply(lambda x: '//' in x)]['oracle_text']

269      NaN
454      NaN
501      NaN
797      NaN
1013     NaN
        ...
24718    NaN
24806    NaN
24829    NaN
24903    NaN
25660    NaN
Name: oracle_text, Length: 155, dtype: object

#### The cards have no oracle text thus they must be dropped

In [36]:
df.drop(df[df['types'].apply(lambda x: '//' in x)].index, inplace=True)
df.reset_index(drop=True, inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25545 entries, 0 to 25544
Data columns (total 26 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   name             25545 non-null  object
 1   cmc              25545 non-null  float64
 2   B                25545 non-null  int64
 3   C                25545 non-null  int64
 4   G                25545 non-null  int64
 5   N                25545 non-null  int64
 6   R                25545 non-null  int64
 7   U                25545 non-null  int64
 8   W                25545 non-null  int64
 9   legendary        25545 non-null  int64
 10  types            25545 non-null  object
 11  sub_types        25545 non-null  object
 12  oracle_text      25099 non-null  object
 13  keywords         25545 non-null  object
 14  power            25545 non-null  object
 15  toughness        25545 non-null  object
 16  textless         25545 non-null  int64
 17  reserved         25545 non-null  int64
 18  rarity_common    25545 non-null  float64
 19  rarity_mythic    25545 non-null  float64
 20  rarity_rare      25545 non-null  float64
 21  rarity_special   25545 non-null  float64
 22  rarity_uncommon  25545 non-null  float64
 23  released_at      25545 non-null  object
 24  booster          25545 non-null  int64
 25  usd              25488 non-null  float64
dtypes: float64(7), int64(11), object(8)
memory usage: 5.1+ MB

In [37]:
types_mlb=MultiLabelBinarizer()
types_mlb.fit(df['types'])
types_mlb.classes_

array(['Artifact', 'Basic', 'Creature', 'Enchantment', 'Instant', 'Land',
       'Planeswalker', 'Snow', 'Sorcery', 'Tribal', 'World'], dtype=object)

In [38]:
binary_types = types_mlb.transform(df['types'])
types_df = pd.DataFrame(binary_types, columns=types_mlb.classes_)
types_df.head()

,Artifact,Basic,Creature,Enchantment,Instant,Land,Planeswalker,Snow,Sorcery,Tribal,World
0,1,0,0,0,0,0,0,0,0,0,0
1,0,0,1,0,0,0,0,0,0,0,0
2,0,0,1,0,0,0,0,0,0,0,0
3,0,0,0,0,0,1,0,0,0,0,0
4,1,0,0,0,0,0,0,0,0,0,0

In [39]:
df.drop('types', axis=1, inplace=True)
df.head()

,name,cmc,B,C,G,N,R,U,W,legendary,...,textless,reserved,rarity_common,rarity_mythic,rarity_rare,rarity_special,rarity_uncommon,released_at,booster,usd
0,+2 Mace,2.0,0,0,0,0,0,0,1,0,...,0,0,1.0,0.0,0.0,0.0,0.0,2021-07-23,1,0.02
1,Aarakocra Sneak,4.0,0,0,0,0,0,1,0,0,...,0,0,1.0,0.0,0.0,0.0,0.0,2022-06-10,1,0.07
2,Abaddon the Despoiler,5.0,1,0,0,0,1,1,0,1,...,0,0,0.0,1.0,0.0,0.0,0.0,2022-10-07,0,2.88
3,Abandoned Outpost,0.0,0,0,0,1,0,0,0,0,...,0,0,1.0,0.0,0.0,0.0,0.0,2001-10-01,1,0.13
4,Abandoned Sarcophagus,3.0,0,1,0,0,0,0,0,0,...,0,0,0.0,0.0,1.0,0.0,0.0,2020-04-17,0,0.08

In [40]:
df = pd.concat([df, types_df], axis=1)
df.head()

,name,cmc,B,C,G,N,R,U,W,legendary,...,Basic,Creature,Enchantment,Instant,Land,Planeswalker,Snow,Sorcery,Tribal,World
0,+2 Mace,2.0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
1,Aarakocra Sneak,4.0,0,0,0,0,0,1,0,0,...,0,1,0,0,0,0,0,0,0,0
2,Abaddon the Despoiler,5.0,1,0,0,0,1,1,0,1,...,0,1,0,0,0,0,0,0,0,0
3,Abandoned Outpost,0.0,0,0,0,1,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
4,Abandoned Sarcophagus,3.0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [41]:
list(df.columns.values)

['name',
 'cmc',
 'B',
 'C',
 'G',
 'N',
 'R',
 'U',
 'W',
 'legendary',
 'sub_types',
 'oracle_text',
 'keywords',
 'power',
 'toughness',
 'textless',
 'reserved',
 'rarity_common',
 'rarity_mythic',
 'rarity_rare',
 'rarity_special',
 'rarity_uncommon',
 'released_at',
 'booster',
 'usd',
 'Artifact',
 'Basic',
 'Creature',
 'Enchantment',
 'Instant',
 'Land',
 'Planeswalker',
 'Snow',
 'Sorcery',
 'Tribal',
 'World']

In [42]:
df = df[['name',
 'cmc',
 'B',
 'C',
 'G',
 'N',
 'R',
 'U',
 'W',
 'legendary',
'Artifact',
 'Basic',
 'Creature',
 'Enchantment',
 'Instant',
 'Land',
 'Planeswalker',
 'Snow',
 'Sorcery',
 'Tribal',
 'World',
 'sub_types',
 'oracle_text',
 'keywords',
 'power',
 'toughness',
 'textless',
 'reserved',
 'rarity_common',
 'rarity_mythic',
 'rarity_rare',
 'rarity_special',
 'rarity_uncommon',
 'released_at',
 'booster',
 'usd'
]]
df.head()

,name,cmc,B,C,G,N,R,U,W,legendary,...,textless,reserved,rarity_common,rarity_mythic,rarity_rare,rarity_special,rarity_uncommon,released_at,booster,usd
0,+2 Mace,2.0,0,0,0,0,0,0,1,0,...,0,0,1.0,0.0,0.0,0.0,0.0,2021-07-23,1,0.02
1,Aarakocra Sneak,4.0,0,0,0,0,0,1,0,0,...,0,0,1.0,0.0,0.0,0.0,0.0,2022-06-10,1,0.07
2,Abaddon the Despoiler,5.0,1,0,0,0,1,1,0,1,...,0,0,0.0,1.0,0.0,0.0,0.0,2022-10-07,0,2.88
3,Abandoned Outpost,0.0,0,0,0,1,0,0,0,0,...,0,0,1.0,0.0,0.0,0.0,0.0,2001-10-01,1,0.13
4,Abandoned Sarcophagus,3.0,0,1,0,0,0,0,0,0,...,0,0,0.0,0.0,1.0,0.0,0.0,2020-04-17,0,0.08

In [43]:
df[['sub_types', 'keywords']].head()

             sub_types                            keywords
0          [Equipment]                             [Equip]
1        [Bird, Rogue]                            [Flying]
2  [Astartes, Warrior]  [Mark of Chaos Ascendant, Trample]
3               [none]                       [no keywords]
4               [none]                       [no keywords]

####